In [18]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

In [19]:
from sklearn.datasets import make_classification

In [20]:
#Create dataset
x,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)
x

array([[ 0.96479937, -0.06644898,  0.98676805, ..., -1.2101605 ,
        -0.62807677,  1.22727382],
       [-0.91651053, -0.56639459, -1.00861409, ..., -0.98453405,
         0.36389642,  0.20947008],
       [-0.10948373, -0.43277388, -0.4576493 , ..., -0.2463834 ,
        -1.05814521, -0.29737608],
       ...,
       [ 1.67463306,  1.75493307,  1.58615382, ...,  0.69272276,
        -1.50384972,  0.22526412],
       [-0.77860873, -0.83568901, -0.19484228, ..., -0.49735437,
         2.47213818,  0.86718741],
       [ 0.24845351, -1.0034389 ,  0.36046013, ...,  0.77323999,
         0.1857344 ,  1.41641179]], shape=(1000, 10))

In [21]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()

In [22]:
log.fit(xtrain,ytrain)
ypred=log.predict(xtest)
ypred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0])

In [23]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(ytest,ypred))
print(confusion_matrix(ytest,ypred))
print(classification_report(ypred,ytest))

0.8466666666666667
[[118  17]
 [ 29 136]]
              precision    recall  f1-score   support

           0       0.87      0.80      0.84       147
           1       0.82      0.89      0.86       153

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



In [24]:
'''Hyperparameter tunning and cross validation'''

'Hyperparameter tunning and cross validation'

In [25]:
model=LogisticRegression()
penality=['l1','l2','elasticnet']
c_values=[100,10,1,0.1,0.01]
solver=['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']

In [26]:
params=dict(penality=penality,C=c_values,solver=solver)

In [27]:
#GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()
grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)


In [28]:
grid

,estimator,LogisticRegression()
,param_grid,"{'C': [100, 10, ...], 'penality': ['l1', 'l2', ...], 'solver': ['lbfgs', 'liblinear', ...]}"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo...shuffle=False)
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l2'


In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Create dataset
X, y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train logistic regression
log = LogisticRegression(max_iter=5000)   # increase iterations for stability
log.fit(X_train, y_train)
y_pred = log.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# Grid search
model = LogisticRegression(max_iter=5000)
param_grid = {
    'penalty': ['l1', 'l2', 'elasticnet', 'none'],
    'C': [100, 10, 1, 0.1, 0.01],
    'solver': ['lbfgs', 'liblinear', 'saga'],
    'l1_ratio': [0.0, 0.5, 1.0]  # only for elasticnet
}

cv = StratifiedKFold(n_splits=5)
grid = GridSearchCV(estimator=model, param_grid=param_grid, scoring='accuracy', cv=cv, n_jobs=-1)
grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)
print("Best CV Accuracy:", grid.best_score_)


In [32]:
#RandomizedSearchCV
from sklearn.model_selection import RandomizedSearchCV
model2=LogisticRegression()
rcv=RandomizedSearchCV(estimator=model,param_distributions=param_grid,cv=5,scoring='accuracy')
rcv.fit(xtrain,ytrain)


c:\Desktop\ds\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Desktop\ds\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Desktop\ds\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Desktop\ds\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Desktop\ds\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
c:\Desktop\ds\venv\lib\site-packages\sklearn\linear_model\_logistic.py

,estimator,LogisticRegre...max_iter=5000)
,param_distributions,"{'C': [100, 10, ...], 'l1_ratio': [0.0, 0.5, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['lbfgs', 'liblinear', ...]}"
,n_iter,10
,scoring,'accuracy'
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,random_state,None
,error_score,nan


In [34]:
rcv.best_score_

np.float64(0.8742857142857143)

In [35]:
rcv.best_params_

{'solver': 'liblinear', 'penalty': 'l2', 'l1_ratio': 1.0, 'C': 0.1}

In [38]:
ypred=rcv.predict(xtest)
print(confusion_matrix(ytest,ypred))

[[120  15]
 [ 29 136]]


In [40]:
#For multiclass Classification
X, y = make_classification(n_samples=1000, n_features=10,n_informative=3, n_classes=3, random_state=42)

In [47]:
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)
logestic=LogisticRegression(multi_class='multinomial')
logestic.fit(xtrain,ytrain)
ypred=logestic.predict(xtest)
print(confusion_matrix(ytest,ypred))
print(accuracy_score(ytest,ypred))

[[76 20  7]
 [25 48 23]
 [ 2 12 87]]
0.7033333333333334


c:\Desktop\ds\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


In [53]:
#Handling Imbalance Datasets
from collections import Counter
x,y=make_classification( n_samples=10000,n_features=2,n_clusters_per_class=1,n_redundant=0,weights=[0.99],random_state=10)

In [54]:
Counter(y)

Counter({np.int64(0): 9846, np.int64(1): 154})

In [57]:
sns.scatterplot(pd.DataFrame(x)[0],pd.DataFrame(x)[1],hue=y)

TypeError: scatterplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given

In [59]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=42)
model=LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['newton-cg','sag','saga']
class_weight=[{0:w,1:v} for w in [1,10,50,100] for v in [1,10,50,100] ]

In [60]:
params=dict(penalty=penalty,C=c_values,solver=solver,class_weight=class_weight)

In [61]:
cv=StratifiedKFold()
grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv)

In [64]:
grid.fit(xtrain,ytrain)
grid.best_params_

c:\Desktop\ds\venv\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Desktop\ds\venv\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Desktop\ds\venv\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Desktop\ds\venv\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Desktop\ds\venv\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Desktop\ds\venv\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ di

{'C': 100,
 'class_weight': {0: 50, 1: 100},
 'penalty': 'l2',
 'solver': 'newton-cg'}

In [66]:
ypred=grid.predict(xtest)
print(accuracy_score(ytest,ypred))
print(confusion_matrix(ytest,ypred))

0.9896
[[2465    0]
 [  26    9]]


In [67]:
from sklearn.metrics import roc_curve,roc_auc_score


In [68]:
x,y=make_classification(n_samples=1000,n_classes=2,random_state=1)
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=1)

In [ ]:
#Created dummy model with default value of 0
dummy=[0 for _ in range(len(ytest))]

In [71]:
model=LogisticRegression()
model.fit(xtrain,ytrain)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [76]:
model = LogisticRegression().fit(X_train, y_train)
model_probabilities = model.predict_proba(X_test)[:, 1]

In [ ]:
#Do later